services:
  - type: web
    name: task-manager-api
    env: ruby
    plan: free
    buildCommand: "bundle install && rake db:migrate"
    startCommand: "bundle exec rails server -e production -p 3000"
    envVars:
      - key: DATABASE_NAME
        value: task_manager_dev
      - key: DATABASE_USERNAME
        value: task_manager
      - key: DATABASE_PASSWORD
        value: P@ssword123
      - key: DATABASE_HOST
        value: localhost
      - key: DATABASE_PORT
        value: 5432
      - key: RAILS_MASTER_KEY
        value: 087463834be03b114d8f613bab5ea205
