default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: task_manager_dev
  username: task_manager
  password: P@ssword123
  host: localhost
  port: 5432

test:
  <<: *default
  database: task_manager_test
  username: task_manager
  password: P@ssword123
  host: localhost
  port: 5432

production:
  <<: *default
  database: task_manager_prod
  username: task_manager
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
